require_relative "../node_modules/react-native/scripts/react_native_pods"
require_relative "../node_modules/@react-native-community/cli-platform-ios/native_modules"

platform :ios, "11.0"
install! "cocoapods", :deterministic_uuids => false

project "app",
  # #MEMO, #TYPE
  "basicDebug" => :debug,
  "basicRelease" => :release,
  "proDebug" => :debug,
  "proRelease" => :release
  # 

target "app" do
  config = use_native_modules!
  flags = get_default_flags()
  # #MEMO, #MODULE: react-native-permissions
  # #ADD:
  permissions_path = "../node_modules/react-native-permissions/ios"
  # 
  # #MEMO, #MODULE: react-native-permissions
  # #MEMO, #MODULE: react-native-camera
  # #ADD:
  pod "Permission-Camera", :path => "#{permissions_path}/Camera"
  # 
  # #MEMO, #MODULE: react-native-permissions
  # #MEMO, #MODULE: @react-native-firebase/messaging
  # #ADD:
  pod "Permission-Notifications", :path => "#{permissions_path}/Notifications"
  # 
  # #MEMO, #MODULE: react-native-permissions
  # #MEMO, #MODULE: react-native-wifi-reborn
  # #ADD:
  pod "Permission-LocationWhenInUse", :path => "#{permissions_path}/LocationWhenInUse"
  # 
  # #MEMO, #MODULE: react-native-permissions
  # #MEMO, #MODULE: react-native-bluetooth-serial-next
  # #ADD:
  pod "Permission-BluetoothPeripheral", :path => "#{permissions_path}/BluetoothPeripheral"
  # 
  # #MEMO, #MODULE: @react-native-google-signin/google-signin
  # #ADD:
  pod "GoogleSignIn", "~> 6.1.0"
  #
  # #MEMO, #MODULE: react-native-fs
  # #ADD:
  pod "RNFS", :path => "../node_modules/react-native-fs"
  #
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  target "appTests" do
    inherit! :complete
  end
  use_flipper!(configurations: [
    # #MEMO, #TYPE
    "basicDebug", 
    "basicRelease", 
    "proDebug", 
    "proRelease"
    # 
  ])
  ENVFILES = {
    # #MEMO, #TYPE
    "basicDebug" => "$(PODS_ROOT)/../../.env.basic",
    "basicRelease" => "$(PODS_ROOT)/../../.env.basic",
    "proDebug" => "$(PODS_ROOT)/../../.env.pro",
    "proRelease" => "$(PODS_ROOT)/../../.env.pro",
    # 
  }
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == "react-native-config"
          config.build_settings["ENVFILE"] = ENVFILES[config.name]
        end
      end
    end
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

# #MEMO, #MODULE: @react-native-firebase/messaging
# #ADD:
target "ImageNotification" do
  pod "Firebase/Messaging", "~> 8.15.0"
end
# 
